### ISSUE TITLE
[FEATURE]How can I start the backend using another port？

### ISSUE THREAD

**Issue by Changmuzi** [whyhow-ai/knowledge-table#31]
## Question

I add port param in backend/src/app/main.py, but it seems that doesn't make. So, how can I change the port?

**Comment by tomsmoker** [comment]
Hey @Changmuzi, if you're running the docker containers, you can change the backend here:

https://github.com/whyhow-ai/knowledge-table/blob/main/backend/docker-compose.yml

With this line:

`command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port {PORT_NUMBER}`

And replace PORT_NUMBER with your desired port.

If you're running it locally, you can run it like this:

`python -m uvicorn app.main:app --host 0.0.0.0 --port {PORT_NUMBER}`
