### ISSUE TITLE
[BUG]{     "detail": "Not Found" }

### ISSUE THREAD

**Issue by happywinder** [whyhow-ai/knowledge-table#36]
## Describe the bug

I deployed the project both in python way and docker way.Although it looked run normally,but i can't upload my file to extract entity relation

## To Reproduce

steps on readme.md

## Expected behavior

{     "detail": "Not Found" } on backend

## Logs and Error Reports

_If applicable, include any relevant console logs or error reports to help diagnose the issue._

## Screenshots
![QQ20241021-154533](https://github.com/user-attachments/assets/8f5808e3-36ab-4bde-883d-91289084c01d)
![QQ20241021-154543](https://github.com/user-attachments/assets/5bfc8357-9c1e-4617-bdd5-8031b86aa460)

_If applicable, add screenshots to help explain your problem._

**Comment by recchris** [comment]
Hey there, 'not found' indicates that a null response was returned, which typically means that the application ran correctly, but an answer was not extracted from your document for that question. Could you please provide some additional details?
- Were you able to upload a document? Did you see any errors in the logs?
- Can you confirm that you copied `.env.sample` to `.env` set an an OpenAI api key? 
- What type of response did you specify (string, list of strings, number, list of numbers, true/false)?
- Did you add any rules?
- etc?

Thx!

**Comment by happywinder** [comment]
> Hey there, 'not found' indicates that a null response was returned, which typically means that the application ran correctly, but an answer was not extracted from your document for that question. Could you please provide some additional details?
> 
> * Were you able to upload a document? Did you see any errors in the logs?
> * Can you confirm that you copied `.env.sample` to `.env` set an an OpenAI api key?
> * What type of response did you specify (string, list of strings, number, list of numbers, true/false)?
> * Did you add any rules?
> * etc?
> 
> Thx!

* I can't upload file，logs didn't show any error.                  Does uploading a file will output in logs? I didn't see any change in console
* i‘m using transit api,i'm not sure thats ok.

**Comment by tomsmoker** [comment]
Hi @happywinder, what's the transit API? Have you changed the port for the frontend or backend?

**Comment by happywinder** [comment]
> Hi @happywinder, what's the transit API? Have you changed the port for the frontend or backend?

I didn't change the port of frontend and backend。I run the project on my lab server,and use command like ssh -L 8889:localhost:5173 -p xxxx xxx@xxxx to show on my PC
Transit API is api bought from api seller

**Comment by recchris** [comment]
Have you tried building the app on your local machine using the `docker-compose up -d --build` command in the README? If you get it running this way, then the backend is accessible at http://localhost:8000, and the frontend is accessible at http://localhost:3000.

If you're installing natively and doing port forwarding, you'll probably need set it up for both the frontend and backend since those apps runs on two separate ports (5173 for the frontend when you run natively, and 8000 for the backend). So you may need to adjust your command to look something like this:

`ssh -L 8889:localhost:5173 -L 8890:localhost:8000 -p xxxx xxx@xxxx`

This way, you should be able to access via:
- Frontend: http://localhost:8889
- Backend: http://localhost:8890

Any additional information you can provide about your setup would be helpful here. Let us know if this works for you. Thx!

**Comment by happywinder** [comment]
> Have you tried building the app on your local machine using the `docker-compose up -d --build` command in the README? If you get it running this way, then the backend is accessible at http://localhost:8000, and the frontend is accessible at http://localhost:3000.
> 
> If you're installing natively and doing port forwarding, you'll probably need set it up for both the frontend and backend since those apps runs on two separate ports (5173 for the frontend when you run natively, and 8000 for the backend). So you may need to adjust your command to look something like this:
> 
> `ssh -L 8889:localhost:5173 -L 8890:localhost:8000 -p xxxx xxx@xxxx`
> 
> This way, you should be able to access via:
> 
> * Frontend: http://localhost:8889
> * Backend: http://localhost:8890
> 
> Any additional information you can provide about your setup would be helpful here. Let us know if this works for you. Thx!

thx,I made success in my local machine. I find my backend port is 8004 and I modified it.^v^
