### ISSUE TITLE
[FEATURE]Is there a limit to api, is 3.5 ok?

### ISSUE THREAD

**Issue by happywinder** [whyhow-ai/knowledge-table#44]
## What

_A clear and concise description of what the feature is. Please include any specific functionality and why this feature would be beneficial to the project._

## Why

_Discuss the impact of this feature on current users, system performance, and any other areas of the application. Indicate if this feature would be beneficial to other users._

## Implementation guidance

_Suggest how this feature might be implemented. Include details like API changes, database schema modifications, architectural considerations, and any other relevant implementation details._

**Comment by tomsmoker** [comment]
Hi @happywinder, the rate limit will be based on the account limits for the OPENAI_API_KEY you set in the .env file or the config. You can also change model in those files too.
