### ISSUE TITLE
Why can the backend shows '{"detail":"Not Found"}'

### ISSUE THREAD

**Issue by xxxxinobody** [whyhow-ai/knowledge-table#53]
Actually, I successfully start the backend, I open the localhost, it shows 
<img width="754" alt="image" src="https://github.com/user-attachments/assets/ea6b793b-3897-411b-b918-bf60db3ea4dc">
and the terminal shows that: 
<img width="531" alt="image" src="https://github.com/user-attachments/assets/9027202e-2126-42e4-86a7-055d271f99be">
Are there any problem in my operation? How to solve this problem?

**Comment by tomsmoker** [comment]
Hey @xxxxinobody, if you're just running the backend, there is nothing at root for a check.  If you want to check, you can go to:

127.0.0.1:800/ping

to check if it's running. However, the backend is just used as an api.  If you want to access the app in browser, you can also use the frontend. What are you trying to use this for? To check if it's running?

**Comment by xxxxinobody** [comment]
I try use: 127.0.0.1:800/ping, it return test: False
![image](https://github.com/user-attachments/assets/76949457-d96c-4250-a259-fb04e9bbb821)
I can start the frontend, but if I upload the file, it returns like that:
![image](https://github.com/user-attachments/assets/509165dd-bc44-4b24-8002-19f32dcb6ac5)
