### ISSUE TITLE
[BUG]can not see Save to Memory in Knowledge-table?

### ISSUE THREAD

**Issue by lwing1966** [whyhow-ai/knowledge-table#72]
## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior_

## Expected behavior

_A clear and concise description of what you expected to happen._

## Logs and Error Reports

_If applicable, include any relevant console logs or error reports to help diagnose the issue._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by chiajy2000** [comment]
Hi lwing, thanks for this - the save to memory feature is not something that is part of the open-source UI, but what we built for clients that wanted to integrate Knowledge Table with the Knowledge Graph Studio.

<img width="1268" alt="Screen Shot 2024-12-15 at 7 37 56 PM" src="https://github.com/user-attachments/assets/23227b2b-1408-4721-89da-3eccce35b227" />

The video we have in the Github Readme reflects the UI that is available in the open-source repo.
