### ISSUE TITLE
where is "Split Cell Into Rows" function？

### ISSUE THREAD

**Issue by lwing1966** [whyhow-ai/knowledge-table#73]

**Comment by chiajy2000** [comment]
You need to make sure that the column type is ‘List of ‘ (i.e. list of numbers, or list of text). Once the column is in that mode, the split cell into rows feature will pop up.

**Comment by recchris** [comment]
Yup, per @chiajy2000's note, you should be able to see it when the column type is set to a list of numbers or text. Screenshot attached

![image](https://github.com/user-attachments/assets/6e69cbbf-bea6-4f93-a52f-1cf0a73f1ce7)

**Comment by lwing1966** [comment]
thx！



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 18, 2024 11:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [whyhow-ai/knowledge-table] where is "Split Cell Into Rows" function？ (Issue #73)




 
Yup, per @chiajy2000's note, you should be able to see it when the column type is set to a list of numbers or text. Screenshot attached
 
image.png (view on web)
